/* eslint-disable  */
import '@babel/polyfill'
import 'expose-loader?jQuery!expose-loader?$!jquery'
import 'jquery-highlight'
import 'expose-loader?ko!knockout'
import 'ecosoft-jqwidgets-patched'
import 'signals'
import 'crossroads'
import 'deep-equal'
import 'ecosoft-excelbuilderjs-node-patched'
import 'file-saver'
import 'hasher'
import 'script-loader!xlsx'
import 'urijs'
import 'escape-html'
import 'xmlbuilder'
import 'ecosoft-pdfjs'